Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/StringLiterals:
  Exclude:
    - 'bin/bundle'

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 198

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/config.ru'
